apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: heater
  name: heater
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: heater
      name: heater
    spec:
      containers:
        - name: heater
          image: heater:latest
          imagePullPolicy: IfNotPresent
          args: ["--rescheduling-time", "10", "--influx-user", "root", "--influx-pass", "root", "--influx-host", "monitoring-influxdb", "--influx-port", "8086", "--influx-database", "k8s"]
          volumeMounts:
          - mountPath: /root/.kube/config 
            name: kubeconfig
            readOnly: true
      volumes:
      - name: kubeconfig
        hostPath:
          path: /etc/kubernetes/scheduler.conf
          type: File
      tolerations:
      - effect: NoSchedule
        operator: Exists
      nodeSelector:
        node-role.kubernetes.io/master: ""
